spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  api-key: ${KAKAO_API_KEY}

security.jwt.token:
  secret-key: testtesttesttesttesttesttesttesttesttesttest
  expire-length: 864000


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha